var annotated_dup =
[
    [ "adc_dev_t", "structadc__dev__t.html", "structadc__dev__t" ],
    [ "adc_mode_t", "structadc__mode__t.html", "structadc__mode__t" ],
    [ "adc_t", "unionadc__t.html", "unionadc__t" ],
    [ "basic_gpio_t", "structbasic__gpio__t.html", "structbasic__gpio__t" ],
    [ "basic_mode_t", "structbasic__mode__t.html", "structbasic__mode__t" ],
    [ "dac_dev", "structdac__dev.html", "structdac__dev" ],
    [ "dac_t", "uniondac__t.html", "uniondac__t" ],
    [ "gpio_dev", "structgpio__dev.html", "structgpio__dev" ],
    [ "gpio_mode_t", "structgpio__mode__t.html", "structgpio__mode__t" ],
    [ "gpio_status_t", "structgpio__status__t.html", "structgpio__status__t" ],
    [ "gpio_t", "uniongpio__t.html", "uniongpio__t" ],
    [ "i2c_dev", "structi2c__dev.html", "structi2c__dev" ],
    [ "i2c_mode_t", "structi2c__mode__t.html", "structi2c__mode__t" ],
    [ "i2c_status_t", "structi2c__status__t.html", "structi2c__status__t" ],
    [ "i2c_t", "unioni2c__t.html", "unioni2c__t" ],
    [ "map_t", "unionmap__t.html", "unionmap__t" ],
    [ "pwm_dev", "structpwm__dev.html", "structpwm__dev" ],
    [ "pwm_t", "unionpwm__t.html", "unionpwm__t" ],
    [ "rtc_t", "unionrtc__t.html", "unionrtc__t" ],
    [ "spi_dev", "structspi__dev.html", "structspi__dev" ],
    [ "spi_mode_t", "structspi__mode__t.html", "structspi__mode__t" ],
    [ "spi_status_t", "structspi__status__t.html", "structspi__status__t" ],
    [ "spi_t", "unionspi__t.html", "unionspi__t" ],
    [ "sys_mode_t", "structsys__mode__t.html", "structsys__mode__t" ],
    [ "sys_status_t", "structsys__status__t.html", "structsys__status__t" ],
    [ "sys_t", "unionsys__t.html", "unionsys__t" ],
    [ "timestamp_t", "uniontimestamp__t.html", "uniontimestamp__t" ],
    [ "tmr_dev_t", "structtmr__dev__t.html", "structtmr__dev__t" ],
    [ "tmr_mode_t", "structtmr__mode__t.html", "structtmr__mode__t" ],
    [ "tmr_t", "uniontmr__t.html", "uniontmr__t" ],
    [ "trace_t", "uniontrace__t.html", "uniontrace__t" ],
    [ "uart_dev_t", "structuart__dev__t.html", "structuart__dev__t" ],
    [ "uart_mode_t", "structuart__mode__t.html", "structuart__mode__t" ],
    [ "uart_status_t", "structuart__status__t.html", "structuart__status__t" ],
    [ "uart_t", "unionuart__t.html", "unionuart__t" ]
];